### ISSUE TITLE
I/flutter ( 7906): Another exception was thrown: 'package:flutter/src/rendering/sliver_multi_box_adaptor.dart': Failed assertion: line 236 pos 16: 'indexOf(child) > index': is not true.

### ISSUE THREAD

**Issue by amoslai5128** [RobertBrunhage/Youtube-Tutorials#3]
When I added more than 7 items,  and I slide down the list and slide up, it shows an error

![image](https://user-images.githubusercontent.com/30002046/60253481-d0943600-98fe-11e9-9fc4-3e60e73fcdf8.png)

I/flutter ( 7906): Another exception was thrown: 'package:flutter/src/widgets/sliver.dart': Failed assertion: line 1059 pos 14: '_childElements.containsKey(index)': is not true.
I/flutter ( 7906): Another exception was thrown: 'package:flutter/src/rendering/sliver_multi_box_adaptor.dart': Failed assertion: line 470 pos 12: 'child.hasSize': is not true.
I/flutter ( 7906): Another exception was thrown: 'package:flutter/src/widgets/sliver.dart': Failed assertion: line 1059 pos 14: '_childElements.containsKey(index)': is not true.
I/flutter ( 7906): Another exception was thrown: 'package:flutter/src/rendering/sliver_multi_box_adaptor.dart': Failed assertion: line 470 pos 12: 'child.hasSize': is not true.
I/flutter ( 7906): Another exception was thrown: 'package:flutter/src/widgets/sliver.dart': Failed assertion: line 1059 pos 14: '_childElements.containsKey(index)': is not true.
I/flutter ( 7906): Another exception was thrown: 'package:flutter/src/rendering/sliver_multi_box_adaptor.dart': Failed assertion: line 470 pos 12: 'child.hasSize': is not true.
I/flutter ( 7906): Another exception was thrown: 'package:flutter/src/widgets/sliver.dart': Failed assertion: line 1059 pos 14: '_childElements.containsKey(index)': is not true.

**Comment by RobertBrunhage** [comment]
What tutorial / code was this from?

**Comment by amoslai5128** [comment]
> What tutorial / code was this from?
On this one: (https://www.youtube.com/watch?v=_j7yKt3vivk)
The error is gone after I change ListView to SliverList, idk why was that

**Comment by RobertBrunhage** [comment]
Okay so I found the problem. The issue is that the Id that is pushed out for the Read button is actually disposed when we scroll down far enough as it's outside of the view. Then, when we try to scroll up we want to BehaviorSubject and **get the id again** which is not possible with a normal `StreamController`.

To fix this we have to introduce RxDart and use `BehaviourSubject` instead of `StreamController` as that will let us listen to the same stream **multiple times** and also **remember the last value** that is pushed out to the stream.

It's also possible to fix with a normal StreamController by adding `Broadcast` to it but that will not remember the Id when we scroll up again. Hence making the button greyed out. I will push up an update with the use of RxDart with some comments.
